"""MolPy — Composable molecular modeling in Python.

Core data structures (``Atom``, ``ForceField``, ``Frame``, …) are imported
eagerly and exposed at the package root — users write ``import molpy as mp``
then ``mp.Frame`` (never ``molpy.core.Frame`` or ``molrs.Frame``). Heavier
subpackages (``io``, ``engine``, ``parser``, …) load lazily on first attribute
access (PEP 562).
"""

# Import version first: version.py runs the molcrafts-molrs compatibility check
# on import, before any molrs-backed core import below, so a stale editable
# build or a mismatched pin surfaces immediately.
from .version import release_date, version

from importlib import import_module
from types import ModuleType
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from . import (
        adapter,
        builder,
        compute,
        data,
        engine,
        io,
        pack,
        parser,
        typifier,
    )

# Submodules are loaded lazily (PEP 562) so that importing a single
# subpackage (e.g. ``molpy.io``) does not eagerly initialize the
# whole io/engine/adapter surface. ``molpy.io`` et al. still work as
# attribute accesses and ``import molpy.io`` works as usual.
_LAZY_SUBMODULES = frozenset(
    {
        "adapter",
        "builder",
        "compute",
        "data",
        "engine",
        "io",
        "pack",
        "parser",
        "typifier",
    }
)


def __getattr__(name: str) -> ModuleType:
    if name in _LAZY_SUBMODULES:
        return import_module(f".{name}", __name__)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(set(globals()) | _LAZY_SUBMODULES)


# =============================================================================
# core/ — every public core symbol is a top-level export (not molpy.core.Foo)
# =============================================================================

from .core.atomistic import (
    Angle,
    Atom,
    Atomistic,
    Bond,
    Dihedral,
    DrudeParticle,
    Improper,
    MasslessSite,
    VirtualSite,
)
from .core.box import Box
from .core.cg import Bead, CGBond, CoarseGrain
from .core.config import Config, get_config
from .core.entity import (
    Entities,
    Entity,
    GraphViews,
    Link,
    NodeRef,
    Refs,
    RelationRef,
)
from .core import fields
from .core.forcefield import (
    AngleClass2BondAngleStyle,
    AngleClass2BondBondStyle,
    AngleClass2Style,
    AngleHarmonicStyle,
    AngleStyle,
    AngleType,
    AtomisticForcefield,
    AtomStyle,
    AtomType,
    BondClass2Style,
    BondHarmonicStyle,
    BondMorseStyle,
    BondStyle,
    BondType,
    DihedralCharmmStyle,
    DihedralClass2Style,
    DihedralFourierStyle,
    DihedralMultiHarmonicStyle,
    DihedralOPLSStyle,
    DihedralPeriodicStyle,
    DihedralStyle,
    DihedralType,
    ForceField,
    ImproperClass2Style,
    ImproperCvffStyle,
    ImproperHarmonicStyle,
    ImproperPeriodicStyle,
    ImproperStyle,
    ImproperType,
    PairBuckStyle,
    PairCoulLongStyle,
    PairCoulTTStyle,
    PairLJ126CoulCutStyle,
    PairLJ126CoulLongStyle,
    PairLJ126Style,
    PairLJClass2Style,
    PairMorseStyle,
    PairStyle,
    PairTholeStyle,
    PairType,
    Parameters,
    Style,
    Type,
)
from .core.ops import (
    FragmentScaling,
    compute_k_ij,
    load_fragment_scaling_data,
    scale_lj,
)
from .core.region import (
    AndRegion,
    BoxRegion,
    Cube,
    NotRegion,
    OrRegion,
    Region,
    SphereRegion,
)
from .core.script import Script, ScriptLanguage
from .core.selector import (
    AtomIndexSelector,
    AtomTypeSelector,
    CoordinateRangeSelector,
    DistanceSelector,
    ElementSelector,
    MaskPredicate,
)
from .core.trajectory import (
    CustomStrategy,
    FrameIntervalStrategy,
    SplitStrategy,
    TimeIntervalStrategy,
    Trajectory,
    TrajectorySplitter,
)
from .core.unit import UnitSystem

# Conformer: molpy subclass with Atomistic marshalling (not bare molrs.Conformer)
from .conformer import Conformer

# =============================================================================
# molrs facade — handwritten identity re-exports (users never import molrs)
# =============================================================================
# Only symbols not already bound above. ``molpy.X is molrs.X`` for each name
# here. Packages that collide with molpy (io / compute / typifier) are omitted.
# Subclasses with real molpy additions (Box, Atomistic, CoarseGrain, Trajectory,
# Conformer, Region) come from core/ above, not from this block.

# Import Frame/Block from the pure-Python layer path so static analysis
# (griffe/mkdocstrings) resolves ``molpy.Frame → molrs.frame.Frame`` without
# going through the top-level ``molrs.Frame`` re-export alias chain.
from molrs.frame import Block, Frame  # noqa: E402

from molrs import (  # noqa: E402
    # Exceptions
    BlockDtypeError,
    UnitsError,
    # Neighbors
    LinkedCell,
    NeighborList,
    NeighborQuery,
    # Frame units / schema (Frame/Block themselves imported above)
    FRAME_SCHEMA_VERSION,
    MetaValue,
    Quantity,
    Unit,
    UnitRegistry,
    # Trajectory observables
    ScalarObservable,
    VectorObservable,
    # I/O
    DCDTrajReader,
    LAMMPSTrajReader,
    TRRTrajReader,
    XTCTrajReader,
    XYZTrajReader,
    parse_smiles,
    read_chgcar_file,
    read_cube_file,
    read_dcd,
    read_gro,
    read_lammps,
    read_lammps_traj,
    read_pdb,
    read_pdb_trajectory,
    read_trr,
    read_xtc,
    read_xyz,
    read_xyz_trajectory,
    write_cube_file,
    write_dcd,
    write_gro,
    write_lammps,
    write_lammps_traj,
    write_pdb,
    write_pdb_trajectory,
    write_trr,
    write_xtc,
    write_xyz,
    SmilesIR,
    # Native geometric regions (molpy Region / SphereRegion live in core/)
    Cuboid,
    HollowSphere,
    Sphere,
    # Graph / chemistry
    Element,
    ExtractedSubgraph,
    Graph,
    Perceive,
    Reaction,
    SmartsMatch,
    SmartsPattern,
    add_hydrogens,
    align_direction,
    compute_gasteiger_charges,
    find_rings,
    perceive_aromaticity,
    rotate,
    scale,
    translate,
    keys,
    # Conformer reports (Conformer class is molpy subclass above)
    ConformerReport,
    ConformerStageReport,
    # Typifiers + charge models
    AtdTypifier,
    BccModel,
    GasteigerModel,
    MMFF94STypifier,
    MMFF94Typifier,
    MullikenModel,
    OPLSAATypifier,
    Typifier,
    # Force-field runtime
    LBFGS,
    OptReport,
    Potentials,
    extract_coords,
    fragment_scaling_data,
    intramolecular_pairs,
    read_forcefield_xml,
    read_forcefield_xml_str,
    read_lammps_forcefield,
    read_lammps_forcefield_str,
    read_opls_xml,
    read_opls_xml_str,
    # Signal helpers
    signal_acf_fft,
    signal_apply_window,
    signal_frequency_grid,
    # Analysis / compute classes
    AngleDistribution,
    CombinedDistribution,
    CombinedDistributionResult,
    DebyeFit,
    DebyeRelaxation,
    DensityGrid,
    DihedralDistribution,
    DistanceDistribution,
    DistributionResult,
    EinsteinConductivity,
    EinsteinDiffusion,
    EinsteinHelfandSpectrum,
    GreenKuboConductivity,
    GreenKuboDiffusion,
    GreenKuboSpectrum,
    HBondCriterion,
    HBonds,
    HBondsResult,
    IRSpectrum,
    LegendreReorientation,
    LegendreReorientationResult,
    LinearFit,
    MolecularMoments,
    Plateau,
    PowerSpectrum,
    RadicalVoronoi,
    RamanSpectrum,
    ResonanceRamanSpectrum,
    RoaSpectrum,
    RunningIntegral,
    SpatialDistribution,
    SpatialDistributionResult,
    VACF,
    VanHove,
    VanHoveResult,
    VcdSpectrum,
    VoronoiCells,
    VoronoiIntegration,
    polarizability_finite_field,
    voronoi_domains,
    voronoi_voids,
    # molrs support modules (not colliding with molpy packages)
    dielectric,
    signal,
    transport,
    validate,
)

__all__ = [
    # Lazy subpackages
    "adapter",
    "builder",
    "compute",
    "data",
    "engine",
    "io",
    "pack",
    "parser",
    "typifier",
    # Version
    "version",
    "release_date",
    # --- core/ (top-level) ---
    "Angle",
    "Atom",
    "Atomistic",
    "Bond",
    "Dihedral",
    "DrudeParticle",
    "Improper",
    "MasslessSite",
    "VirtualSite",
    "Box",
    "Bead",
    "CGBond",
    "CoarseGrain",
    "Config",
    "get_config",
    "Entities",
    "Entity",
    "GraphViews",
    "Link",
    "NodeRef",
    "Refs",
    "RelationRef",
    "fields",
    "AngleClass2BondAngleStyle",
    "AngleClass2BondBondStyle",
    "AngleClass2Style",
    "AngleHarmonicStyle",
    "AngleStyle",
    "AngleType",
    "AtomisticForcefield",
    "AtomStyle",
    "AtomType",
    "BondClass2Style",
    "BondHarmonicStyle",
    "BondMorseStyle",
    "BondStyle",
    "BondType",
    "DihedralCharmmStyle",
    "DihedralClass2Style",
    "DihedralFourierStyle",
    "DihedralMultiHarmonicStyle",
    "DihedralOPLSStyle",
    "DihedralPeriodicStyle",
    "DihedralStyle",
    "DihedralType",
    "ForceField",
    "ImproperClass2Style",
    "ImproperCvffStyle",
    "ImproperHarmonicStyle",
    "ImproperPeriodicStyle",
    "ImproperStyle",
    "ImproperType",
    "PairBuckStyle",
    "PairCoulLongStyle",
    "PairCoulTTStyle",
    "PairLJ126CoulCutStyle",
    "PairLJ126CoulLongStyle",
    "PairLJ126Style",
    "PairLJClass2Style",
    "PairMorseStyle",
    "PairStyle",
    "PairTholeStyle",
    "PairType",
    "Parameters",
    "Style",
    "Type",
    "FragmentScaling",
    "compute_k_ij",
    "load_fragment_scaling_data",
    "scale_lj",
    "AndRegion",
    "BoxRegion",
    "Cube",
    "NotRegion",
    "OrRegion",
    "Region",
    "SphereRegion",
    "Script",
    "ScriptLanguage",
    "AtomIndexSelector",
    "AtomTypeSelector",
    "CoordinateRangeSelector",
    "DistanceSelector",
    "ElementSelector",
    "MaskPredicate",
    "CustomStrategy",
    "FrameIntervalStrategy",
    "SplitStrategy",
    "TimeIntervalStrategy",
    "Trajectory",
    "TrajectorySplitter",
    "UnitSystem",
    "Conformer",
    # --- molrs identity re-exports ---
    "BlockDtypeError",
    "UnitsError",
    "LinkedCell",
    "NeighborList",
    "NeighborQuery",
    "Block",
    "FRAME_SCHEMA_VERSION",
    "Frame",
    "MetaValue",
    "Quantity",
    "Unit",
    "UnitRegistry",
    "ScalarObservable",
    "VectorObservable",
    "DCDTrajReader",
    "LAMMPSTrajReader",
    "TRRTrajReader",
    "XTCTrajReader",
    "XYZTrajReader",
    "parse_smiles",
    "read_chgcar_file",
    "read_cube_file",
    "read_dcd",
    "read_gro",
    "read_lammps",
    "read_lammps_traj",
    "read_pdb",
    "read_pdb_trajectory",
    "read_trr",
    "read_xtc",
    "read_xyz",
    "read_xyz_trajectory",
    "write_cube_file",
    "write_dcd",
    "write_gro",
    "write_lammps",
    "write_lammps_traj",
    "write_pdb",
    "write_pdb_trajectory",
    "write_trr",
    "write_xtc",
    "write_xyz",
    "SmilesIR",
    "Cuboid",
    "HollowSphere",
    "Sphere",
    "Element",
    "ExtractedSubgraph",
    "Graph",
    "Perceive",
    "Reaction",
    "SmartsMatch",
    "SmartsPattern",
    "add_hydrogens",
    "align_direction",
    "compute_gasteiger_charges",
    "find_rings",
    "perceive_aromaticity",
    "rotate",
    "scale",
    "translate",
    "keys",
    "ConformerReport",
    "ConformerStageReport",
    "AtdTypifier",
    "BccModel",
    "GasteigerModel",
    "MMFF94STypifier",
    "MMFF94Typifier",
    "MullikenModel",
    "OPLSAATypifier",
    "Typifier",
    "LBFGS",
    "OptReport",
    "Potentials",
    "extract_coords",
    "fragment_scaling_data",
    "intramolecular_pairs",
    "read_forcefield_xml",
    "read_forcefield_xml_str",
    "read_lammps_forcefield",
    "read_lammps_forcefield_str",
    "read_opls_xml",
    "read_opls_xml_str",
    "signal_acf_fft",
    "signal_apply_window",
    "signal_frequency_grid",
    "AngleDistribution",
    "CombinedDistribution",
    "CombinedDistributionResult",
    "DebyeFit",
    "DebyeRelaxation",
    "DensityGrid",
    "DihedralDistribution",
    "DistanceDistribution",
    "DistributionResult",
    "EinsteinConductivity",
    "EinsteinDiffusion",
    "EinsteinHelfandSpectrum",
    "GreenKuboConductivity",
    "GreenKuboDiffusion",
    "GreenKuboSpectrum",
    "HBondCriterion",
    "HBonds",
    "HBondsResult",
    "IRSpectrum",
    "LegendreReorientation",
    "LegendreReorientationResult",
    "LinearFit",
    "MolecularMoments",
    "Plateau",
    "PowerSpectrum",
    "RadicalVoronoi",
    "RamanSpectrum",
    "ResonanceRamanSpectrum",
    "RoaSpectrum",
    "RunningIntegral",
    "SpatialDistribution",
    "SpatialDistributionResult",
    "VACF",
    "VanHove",
    "VanHoveResult",
    "VcdSpectrum",
    "VoronoiCells",
    "VoronoiIntegration",
    "polarizability_finite_field",
    "voronoi_domains",
    "voronoi_voids",
    "dielectric",
    "signal",
    "transport",
    "validate",
]
