"""Experimental. Data file writer factory functions — molrs-backed.

Signature-compatible with :mod:`molpy.io.writers`; delegates to
:mod:`molrs.io` under the hood.  See :ref:`molrs-io-experimental`
for the graduation plan.
"""

from pathlib import Path
from typing import Any

PathLike = str | Path


# =============================================================================
# Data File Writers
# =============================================================================


def write_lammps_data(file: PathLike, frame: Any, atom_style: str = "full") -> None:
    """Experimental. Write LAMMPS data file via molrs backend.

    .. deprecated::
        Use :func:`molpy.io.write_lammps_data` for the stable implementation.
    """
    from .data.lammps import LammpsDataWriter

    writer = LammpsDataWriter(Path(file), atom_style=atom_style)
    writer.write(frame)


def write_pdb(file: PathLike, frame: Any) -> None:
    """Experimental. Write PDB file via molrs backend.

    .. deprecated::
        Use :func:`molpy.io.write_pdb` for the stable implementation.
    """
    from .data.pdb import PDBWriter

    writer = PDBWriter(Path(file))
    writer.write(frame)


def write_xyz(file: PathLike, frame: Any) -> None:
    """Experimental. Write XYZ file.

    This is a new function with no equivalent in :mod:`molpy.io.writers`.
    When the experimental layer graduates, it will become the canonical
    ``molpy.io.write_xyz``.
    """
    import numpy as np

    atoms = frame["atoms"]
    n_atoms = atoms.nrows
    lines = [f"{n_atoms}\n", f"Generated by molpy.io.experimental.write_xyz\n"]

    element = atoms.get("element", None)
    x, y, z = atoms["x"], atoms["y"], atoms["z"]

    for i in range(n_atoms):
        sym = str(element[i]) if element is not None else "X"
        lines.append(f"{sym} {x[i]:.6f} {y[i]:.6f} {z[i]:.6f}\n")

    with open(str(file), "w") as fh:
        fh.writelines(lines)
