"""
Data file reader factory functions.

This module provides convenient factory functions for creating various data file readers.
All functions return Frame objects by populating an optional frame parameter.
"""

from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .log.lammps import LAMMPSLog

PathLike = str | Path


# Lazy import to avoid loading all dependencies
def _ensure_frame(frame):
    """Ensure a Frame object exists."""
    if frame is None:
        from molrs import Frame

        return Frame()
    return frame


# =============================================================================
# Data File Readers
# =============================================================================


def read_lammps_data(file: PathLike, atom_style: str, frame: Any = None) -> Any:
    """
    Read a LAMMPS data file and return its explicit parse products.

    Args:
        file: Path to LAMMPS data file
        atom_style: LAMMPS atom style (e.g., 'full', 'atomic')
        frame: Optional existing Frame to populate

    Returns:
        ``LammpsDataResult`` with ``frame``, ``forcefield``, ``counts``, and
        ``type_labels``. Callers must select the product they consume.
    """
    from .data.lammps import LammpsDataReader

    reader = LammpsDataReader(Path(file), atom_style)
    return reader.read(frame=frame)


def read_lammps_molecule(file: PathLike, frame: Any = None) -> Any:
    """
    Read LAMMPS molecule file and return a Frame object.

    Args:
        file: Path to LAMMPS molecule file
        frame: Optional existing Frame to populate

    Returns:
        Populated Frame object
    """
    from .data.lammps_molecule import LammpsMoleculeReader

    reader = LammpsMoleculeReader(Path(file))
    return reader.read(frame=frame)


def read_pdb(file: PathLike, frame: Any = None) -> Any:
    """Read a PDB file (molrs); CONECT pairs are de-duplicated.

    Args:
        file: Path to PDB file.
        frame: Accepted for API parity; ignored (molrs returns a new Frame).

    Returns:
        :class:`~molpy.Frame` for the first MODEL.
    """
    from .data.pdb import PDBReader

    del frame
    return PDBReader(Path(file)).read()


def read_amber_inpcrd(inpcrd: PathLike, frame: Any = None) -> Any:
    """
    Read AMBER inpcrd file and return a Frame object.

    Args:
        inpcrd: Path to AMBER inpcrd file
        frame: Optional existing Frame to populate

    Returns:
        Populated Frame object
    """
    from .data.amber import AmberInpcrdReader

    frame = _ensure_frame(frame)
    reader = AmberInpcrdReader(Path(inpcrd))
    return reader.read(frame)


def read_amber_ac(file: PathLike, frame: Any = None) -> Any:
    """
    Read AC file and return a Frame object.

    Args:
        file: Path to AC file
        frame: Optional existing Frame to populate

    Returns:
        Populated Frame object
    """
    from .data.ac import AcReader

    frame = _ensure_frame(frame)
    reader = AcReader(Path(file))
    return reader.read(frame)


def read_amber_frcmod(file: PathLike) -> dict[str, Any]:
    """
    Read an AMBER FRCMOD file.

    FRCMOD files contain additional force field parameters generated by parmchk2.

    Args:
        file: Path to FRCMOD file

    Returns:
        Dictionary with sections: 'remark', 'mass', 'bond', 'angle', 'dihe',
        'improper', 'nonbon', and 'raw_text'.
    """
    from .forcefield.frcmod import read_frcmod

    return read_frcmod(file)


def read_mol2(file: PathLike, frame: Any = None) -> Any:
    """Read a Tripos MOL2 file (molrs; first molecule).

    Args:
        file: Path to a ``.mol2`` file.
        frame: Accepted for API parity; ignored (molrs returns a new Frame).

    Returns:
        Canonical :class:`~molpy.Frame`.
    """
    from .data.mol2 import Mol2Reader

    del frame
    return Mol2Reader(Path(file)).read()


def read_xsf(file: PathLike, frame: Any = None) -> Any:
    """
    Read XSF file and return a Frame object.

    Args:
        file: Path to XSF file
        frame: Optional existing Frame to populate

    Returns:
        Populated Frame object
    """
    from .data.xsf import XsfReader

    reader = XsfReader(Path(file))
    return reader.read(frame)


def read_gro(file: PathLike, frame: Any = None) -> Any:
    """Read a GROMACS GRO file (molrs); returns the first frame.

    Args:
        file: Path to ``.gro`` file.
        frame: Accepted for API parity; ignored.

    Returns:
        :class:`~molpy.Frame`.
    """
    from .data.gro import GroReader

    del frame
    return GroReader(Path(file)).read()


def read_xyz(file: PathLike, frame: Any = None) -> Any:
    """Read an XYZ file (molrs) with molpy column normalization.

    Args:
        file: Path to XYZ file.
        frame: Accepted for API parity; ignored.

    Returns:
        :class:`~molpy.Frame`.
    """
    from .data.xyz import XYZReader

    del frame
    return XYZReader(Path(file)).read()


# =============================================================================
# Force Field Readers
# =============================================================================


def read_lammps_forcefield(scripts: PathLike | list[PathLike]) -> Any:
    """
    Read a LAMMPS force-field include (``*.ff``) into a ForceField.

    Delegates to the native molrs reader (``molrs.ff.read_lammps_forcefield``),
    which parses the include directly into a ``molrs.ff.ForceField`` in molrs units
    (Å, kcal/mol, radians, e): LAMMPS harmonic ``K`` → molrs ``k = 2K``, angle
    and dihedral-phase values are converted degrees → radians, and
    ``dihedral_style fourier``
    maps to the molrs ``periodic`` kernel. AMBER 1-4 scaling is recorded on the
    force field's special bonds. Per-atom charge and mass live in the LAMMPS
    *data* file, not this include, so they are not read here.

    Args:
        scripts: Path (or list of paths) to LAMMPS force-field include(s). A
            list is concatenated and parsed as a single document.

    Returns:
        ``molpy.ForceField`` (which is ``molrs.ff.ForceField``).
    """
    import molrs

    paths = scripts if isinstance(scripts, list) else [scripts]
    if len(paths) == 1:
        return molrs.ff.read_lammps_forcefield(str(paths[0]))
    text = "\n".join(Path(p).read_text() for p in paths)
    return molrs.ff.read_lammps_forcefield_str(text)


# Identity re-export onto molpy.io only (no package-root mp.read_*).
from .forcefield.xml import read_xml_forcefield as read_xml_forcefield  # noqa: E402


def read_amber(
    prmtop: PathLike, inpcrd: PathLike | None = None, frame: Any = None
) -> Any:
    """
    Read AMBER prmtop and optional inpcrd files.

    Args:
        prmtop: Path to AMBER prmtop file
        inpcrd: Optional path to AMBER inpcrd file
        frame: Optional existing Frame to populate

    Returns:
        Tuple of (Frame, ForceField)
    """
    from .forcefield.amber import AmberPrmtopReader

    frame = _ensure_frame(frame)
    prmtop_path = Path(prmtop)
    reader = AmberPrmtopReader(prmtop_path)
    frame, ff = reader.read(frame)

    if inpcrd is not None:
        from .data.amber import AmberInpcrdReader

        inpcrd_reader = AmberInpcrdReader(Path(inpcrd))
        frame = inpcrd_reader.read(frame)

    return frame, ff


def read_top(file: PathLike, forcefield: Any = None) -> Any:
    """
    Read GROMACS topology file and return a ForceField object.

    Args:
        file: Path to GROMACS .top file
        forcefield: Optional existing ForceField to populate

    Returns:
        Populated ForceField object
    """
    from molpy.core.forcefield import ForceField

    from .forcefield.top import GromacsTopReader

    if forcefield is None:
        forcefield = ForceField()

    reader = GromacsTopReader(Path(file))
    return reader.read(forcefield)


# =============================================================================
# Trajectory Readers
# =============================================================================


def read_lammps_trajectory(traj: PathLike) -> Any:
    """
    Read LAMMPS trajectory file and return a trajectory reader.

    Backed by the molrs Rust lazy reader.

    Args:
        traj: Path to LAMMPS trajectory file
    Returns:
        molrs ``TrajectoryReader`` object
    """
    import molrs.io

    return molrs.io.read_lammps_trajectory(str(traj))


def read_xyz_trajectory(file: PathLike) -> Any:
    """
    Read XYZ trajectory file and return a trajectory reader.

    Backed by the molrs Rust lazy reader.

    Args:
        file: Path to XYZ trajectory file

    Returns:
        molrs ``TrajectoryReader`` object
    """
    import molrs.io

    return molrs.io.read_xyz_trajectory(str(file))


def read_pdb_trajectory(file: PathLike) -> list:
    """Read every model of a (multi-frame) PDB file as a list of Frames.

    Each ``MODEL``/``END``-delimited block becomes one Frame. A single-model PDB
    yields a one-element list. Backed by the molrs Rust reader.
    """
    import molrs.io

    # molrs.io.read_pdb_trajectory already returns canonical rich Frames.
    return list(molrs.io.read_pdb_trajectory(str(file)))


def read_dcd_trajectory(file: PathLike) -> Any:
    """Read a DCD trajectory and return a lazy trajectory reader.

    Backed by the molrs Rust lazy reader (O(1) random access by frame index).

    Args:
        file: Path to a ``.dcd`` file.

    Returns:
        molrs ``TrajectoryReader`` object.
    """
    import molrs.io

    return molrs.io.read_dcd_trajectory(str(file))


def read_trr_trajectory(file: PathLike) -> Any:
    """Read a GROMACS TRR trajectory and return a lazy trajectory reader.

    Backed by the molrs Rust lazy reader (single/double precision, coordinates
    plus velocities/forces when present; O(1) random access).

    Args:
        file: Path to a ``.trr`` file.

    Returns:
        molrs ``TrajectoryReader`` object.
    """
    import molrs.io

    return molrs.io.read_trr_trajectory(str(file))


def read_xtc_trajectory(file: PathLike) -> Any:
    """Read a GROMACS XTC (compressed) trajectory and return a lazy reader.

    Backed by the molrs Rust lazy reader (lossy compression; accepts classic
    1995 and 2023 magic; O(1) random access after a one-time index scan).

    Args:
        file: Path to a ``.xtc`` file.

    Returns:
        molrs ``TrajectoryReader`` object.
    """
    import molrs.io

    return molrs.io.read_xtc_trajectory(str(file))


def read_cube(file: PathLike) -> Any:
    """Read a Gaussian Cube file into a Frame with a grid block (molrs)."""
    import molrs.io

    return molrs.io.read_cube(str(file))


def read_chgcar(file: PathLike) -> Any:
    """Read a VASP CHGCAR into a Frame with a ``chgcar`` grid block (molrs)."""
    import molrs.io

    return molrs.io.read_chgcar(str(file))


# =============================================================================
# Log Readers
# =============================================================================


def read_LAMMPS_log(file: PathLike) -> "LAMMPSLog":
    """
    Read a LAMMPS log file and return a nested dataclass result.

    Args:
        file: Path to LAMMPS log file

    Returns:
        Parsed ``LAMMPSLog`` object.
    """
    from .log.lammps import read_LAMMPS_log as _read_LAMMPS_log

    return _read_LAMMPS_log(Path(file))


def read_smiles(smiles: str) -> Any:
    """Parse a single-component SMILES string into an :class:`Atomistic`.

    Connectivity only: hydrogens implicit in the SMILES are **not** added, and
    no coordinates are generated. Filling open valences is a separate
    perception step (``mp.Perceive().find_hydrogens(mol)``), and 3D embedding a
    separate conformer step — :class:`~molpy.io.SmilesReader` composes all
    three when you want the finished molecule.

    This is an **io** entry point, not a constructor on the graph. A SMILES
    string is a file format, and the layering runs io → core: a core type that
    could parse one would make the graph depend on the parser.

    Args:
        smiles: A SMILES string naming exactly one connected molecule.

    Returns:
        The parsed graph.

    Raises:
        ValueError: if ``smiles`` is syntactically invalid, or names more than
            one component. A ``'.'``-separated string is a *set* of molecules,
            not a molecule; take them apart with
            ``mp.SmilesIR(smiles).components()``.

    Examples:
        >>> import molpy as mp
        >>> len(list(mp.io.read_smiles("CCO").atoms))
        3
    """
    import molrs

    from molpy.core.atomistic import Atomistic

    ir = molrs.io.SmilesIR(smiles)
    if ir.n_components != 1:
        raise ValueError(
            f"read_smiles needs one component, {smiles!r} has "
            f"{ir.n_components}. Use mp.SmilesIR(smiles).components() and "
            "adopt each, or pass one component at a time."
        )
    return Atomistic.adopt(ir.to_atomistic())


def write_smarts(
    mol: Any,
    center: Any,
    *,
    reach: int = 1,
    atomic_number: bool = True,
    include_degree: bool = True,
    include_h_count: bool = True,
    include_charge: bool = True,
    include_aromatic: bool = True,
    include_ring_membership: bool = False,
    include_ring_size: bool = False,
    include_explicit_h_atoms: bool = False,
    include_bond_orders: bool = True,
    neighbor_style: str = "chain",
    canonical_neighbor_order: bool = True,
) -> str:
    """Encode the local topology around ``center`` as a SMARTS string.

    Thin wrap of ``molrs.io.write_smarts``. Science flags match the molrs
    ``LocalSmartsOptions`` surface. This is an io entry — not a method on
    :class:`~molpy.core.atomistic.Atomistic`.

    Args:
        mol: molpy :class:`~molpy.core.atomistic.Atomistic` (or molrs graph).
        center: Atom view (``.handle``) or integer handle.
        reach: Bond radius of the local ball (must be >= 1).
        atomic_number: Use ``[#Z]`` rather than elemental symbols.
        include_degree: Add Daylight ``D`` on the center.
        include_h_count: Add ``H`` on the center.
        include_charge: Add formal charge when nonzero.
        include_aromatic: Mark aromatic atoms / bonds.
        include_ring_membership: Add ring-count primitives.
        include_ring_size: Add smallest-ring size.
        include_explicit_h_atoms: Keep explicit hydrogens in the ball.
        include_bond_orders: Emit ``=`` / ``#`` / ``:`` when not single.
        neighbor_style: ``"chain"`` or ``"recursive"``.
        canonical_neighbor_order: Sort neighbors by canonical atom order.

    Returns:
        A SMARTS string that matches ``center`` in ``mol``.
    """
    import molrs

    handle = int(getattr(center, "handle", center))
    return molrs.io.write_smarts(
        mol,
        handle,
        reach=reach,
        atomic_number=atomic_number,
        include_degree=include_degree,
        include_h_count=include_h_count,
        include_charge=include_charge,
        include_aromatic=include_aromatic,
        include_ring_membership=include_ring_membership,
        include_ring_size=include_ring_size,
        include_explicit_h_atoms=include_explicit_h_atoms,
        include_bond_orders=include_bond_orders,
        neighbor_style=neighbor_style,
        canonical_neighbor_order=canonical_neighbor_order,
    )
