#!/usr/bin/env python3
"""
Example demonstrating the Self-Avoiding Random Walk (SARW) builder.

This example shows how to:
1. Create a self-avoiding random walk lattice/position generator
2. Use RandomWalkBuilder to place monomers along the walk
3. Use SAWPolymerBuilder to create connected polymer chains
4. Compare different builder approaches
5. Export structures to LAMMPS data files
6. Generate basic force field parameters
"""

import numpy as np
from pathlib import Path
from molpy.core.atomistic import AtomicStructure
from molpy.core.forcefield import ForceField
from molpy.builder import (
    RandomWalkLattice, 
    RandomWalkBuilder, 
    SAWPolymerBuilder,
    CrystalBuilder,
    FCCBuilder
)
from molpy.io.data.lammps import LammpsDataWriter
from molpy.io.forcefield.lammps import LAMMPSForceFieldReader

def write_lammps_files(structure: AtomicStructure, basename: str, output_dir: str = "output"):
    """
    Write LAMMPS data file and basic force field for a structure.
    
    Args:
        structure: AtomicStructure to export
        basename: Base name for output files
        output_dir: Output directory
    """
    output_path = Path(output_dir)
    output_path.mkdir(exist_ok=True)
    
    try:
        # Convert AtomicStructure to Frame (needed for LAMMPS writer)
        frame = structure.to_frame()
        
        # Set up basic force field
        if not hasattr(frame, 'forcefield') or frame.forcefield is None:
            frame.forcefield = ForceField()
            frame.forcefield.unit = "real"  # LAMMPS real units
        
        # Write LAMMPS data file
        data_file = output_path / f"{basename}.data"
        writer = LammpsDataWriter(data_file)
        writer.write(frame)
        
        print(f"✓ Written LAMMPS data file: {data_file}")
        
        # Generate basic force field script
        script_file = output_path / f"{basename}.in"
        write_basic_lammps_script(script_file, data_file.name, frame)
        
        print(f"✓ Written LAMMPS input script: {script_file}")
        
        return data_file, script_file
        
    except Exception as e:
        print(f"✗ Error writing LAMMPS files: {e}")
        import traceback
        traceback.print_exc()
        return None, None

def write_basic_lammps_script(script_file: Path, data_file: str, frame):
    """Write a basic LAMMPS input script."""
    
    script_content = f"""# LAMMPS input script for SARW polymer
# Generated by molpy SARW builder example

# Initialization
units real
dimension 3
boundary p p p
atom_style full

# Read data file
read_data {data_file}

# Force field parameters (basic LJ + harmonic bonds)
pair_style lj/cut 12.0

# Basic parameters for carbon atoms (adjust as needed)
pair_coeff 1 1 0.07 3.4  # C-C interaction (epsilon, sigma)

# Bond parameters (if bonds exist)
bond_style harmonic
bond_coeff 1 350.0 1.54  # C-C bond (K, r0)

# Basic simulation settings
neighbor 2.0 bin
neigh_modify delay 0 every 1 check yes

# Minimize energy
minimize 1.0e-6 1.0e-8 1000 10000

# Output
dump 1 all atom 100 {script_file.stem}_trajectory.lammpstrj
thermo 100
thermo_style full

# Short MD run
timestep 1.0
fix 1 all nve
run 1000

# Final output
write_data {script_file.stem}_final.data
"""
    
    with open(script_file, 'w') as f:
        f.write(script_content)

def create_simple_monomer(element: str = "C") -> AtomicStructure:
    """Create a simple single-atom monomer template."""
    monomer = AtomicStructure(f"{element}_monomer")
    monomer.def_atom(name=element, element=element, xyz=[0.0, 0.0, 0.0])
    return monomer

def create_ch2_monomer() -> AtomicStructure:
    """Create a simple CH2 monomer unit."""
    monomer = AtomicStructure("CH2_monomer")
    
    # Carbon at origin
    monomer.def_atom(name="C1", element="C", xyz=[0.0, 0.0, 0.0])
    
    # Two hydrogens
    monomer.def_atom(name="H1", element="H", xyz=[0.6, 0.6, 0.0])
    monomer.def_atom(name="H2", element="H", xyz=[-0.6, 0.6, 0.0])
    
    return monomer

def example_1_basic_sarw_lattice():
    """Example 1: Basic SARW position generation."""
    print("=== Example 1: Basic SARW Lattice ===")
    
    # Create a random walk lattice generator
    sarw_lattice = RandomWalkLattice(
        step_length=1.5,    # Distance between steps
        max_attempts=1000,  # Max attempts per step
        seed=42             # For reproducible results
    )
    
    # Generate positions for a 10-step walk
    positions = sarw_lattice.generate_positions(
        n_steps=10,
        start_pos=np.array([0.0, 0.0, 0.0]),
        exclusion_radius=1.0
    )
    
    print(f"Generated {len(positions)} positions")
    print(f"First few positions:\n{positions[:5]}")
    print(f"Final position: {positions[-1]}")
    
    # Calculate some statistics
    distances = np.linalg.norm(np.diff(positions, axis=0), axis=1)
    print(f"Step lengths: mean={np.mean(distances):.2f}, std={np.std(distances):.2f}")
    
    return positions

def example_2_random_walk_builder():
    """Example 2: Using RandomWalkBuilder to create a polymer."""
    print("\n=== Example 2: RandomWalkBuilder ===")
    
    # Create a simple carbon monomer
    carbon_monomer = create_simple_monomer("C")
    
    # Create the builder
    builder = RandomWalkBuilder(
        step_length=1.4,    # C-C bond length
        max_attempts=500,
        seed=123
    )
    
    # Build a polymer chain
    polymer = builder.build(
        monomer_template=carbon_monomer,
        n_monomers=15,
        start_position=np.array([0.0, 0.0, 0.0]),
        name="carbon_chain"
    )
    
    print(f"Created polymer '{polymer.get('name', 'polymer')}' with {len(polymer.atoms)} atoms")
    
    return polymer

def example_3_saw_polymer_builder():
    """Example 3: Using SAWPolymerBuilder with connectivity."""
    print("\n=== Example 3: SAWPolymerBuilder with Bonds ===")
    
    # Create a CH2 monomer unit
    ch2_monomer = create_ch2_monomer()
    
    # Create the SAW polymer builder
    saw_builder = SAWPolymerBuilder(
        step_length=1.54,   # C-C bond length in polyethylene
        max_attempts=800,
        seed=456
    )
    
    # Build a connected polymer
    polyethylene = saw_builder.build_connected_polymer(
        monomer_template=ch2_monomer,
        n_monomers=8,
        bond_length=1.54,
        start_position=np.array([0.0, 0.0, 0.0]),
        name="polyethylene_chain"
    )
    
    print(f"Created polymer '{polyethylene.get('name', 'polyethylene')}'")
    print(f"  Atoms: {len(polyethylene.atoms)}")
    print(f"  Bonds: {len(polyethylene.bonds)}")
    
    # Show bond information
    if hasattr(polyethylene, 'bonds') and len(polyethylene.bonds) > 0:
        bond_lengths = []
        for bond in polyethylene.bonds:
            if hasattr(bond, 'length'):
                bond_lengths.append(bond['length'])
        if bond_lengths:
            print(f"  Bond lengths: {len(bond_lengths)} bonds, target length: {bond_lengths[0]}")
    
    return polyethylene

def example_4_comparison_with_crystal_builder():
    """Example 4: Compare SARW with regular crystal builder."""
    print("\n=== Example 4: Comparison with Crystal Builder ===")
    
    # Create a simple region for comparison
    class SimpleBoxRegion:
        def __init__(self, size):
            self.size = size
            self._bounds = np.array([[-size/2, -size/2, -size/2], 
                                   [size/2, size/2, size/2]])
        
        @property
        def bounds(self):
            return self._bounds
            
        def isin(self, points):
            points = np.asarray(points)
            if points.ndim == 1:
                points = points.reshape(1, -1)
            return np.all((points >= self._bounds[0]) & (points <= self._bounds[1]), axis=1)
        
        def bounding_box(self):
            """Add bounding_box method for compatibility."""
            return self._bounds[0], self._bounds[1]
    
    region = SimpleBoxRegion(5.0)
    
    # FCC crystal builder
    fcc_builder = FCCBuilder(a=2.0)
    atom_template = create_simple_monomer("Au")
    
    try:
        fcc_structure = fcc_builder.build(region, atom_template, "fcc_gold")
        print(f"FCC structure: {len(fcc_structure.atoms)} atoms in regular lattice")
    except Exception as e:
        print(f"FCC builder error: {e}")
    
    # SARW builder for comparison
    sarw_builder = RandomWalkBuilder(step_length=2.0, seed=789)
    sarw_structure = sarw_builder.build(
        monomer_template=atom_template,
        n_monomers=20,  # Arbitrary number
        name="sarw_gold"
    )
    
    print(f"SARW structure: {len(sarw_structure.atoms)} atoms in random walk")
    print("Key difference: SARW creates linear chains, FCC creates 3D crystals")

def export_to_lammps(structure, filename):
    """Export a structure to LAMMPS data file."""
    writer = LammpsDataWriter(filename)
    writer.write(structure)
    print(f"Exported structure to {filename}")

def example_5_generate_lammps_files():
    """Example 5: Generate LAMMPS data and input files."""
    print("\n=== Example 5: Generate LAMMPS Files ===")
    
    # Create a polyethylene chain with SARW builder
    ch2_monomer = create_ch2_monomer()
    saw_builder = SAWPolymerBuilder(
        step_length=1.54,
        max_attempts=800,
        seed=999
    )
    
    # Build polymer
    polymer = saw_builder.build_connected_polymer(
        monomer_template=ch2_monomer,
        n_monomers=10,
        bond_length=1.54,
        start_position=np.array([0.0, 0.0, 0.0]),
        name="polyethylene_sarw"
    )
    
    print(f"Generated polymer with {len(polymer.atoms)} atoms and {len(polymer.bonds)} bonds")
    
    # Write LAMMPS files
    data_file, script_file = write_lammps_files(polymer, "polyethylene_sarw")
    
    if data_file and script_file:
        print(f"LAMMPS files written successfully!")
        print(f"  Data file: {data_file}")
        print(f"  Input script: {script_file}")
        print("  Run with: lammps -in polyethylene_sarw.in")
    
    return polymer

def main():
    """Run all examples."""
    print("Self-Avoiding Random Walk (SARW) Builder Examples")
    print("=" * 50)
    
    try:
        # Run examples
        positions = example_1_basic_sarw_lattice()
        carbon_chain = example_2_random_walk_builder()
        polyethylene = example_3_saw_polymer_builder()
        example_4_comparison_with_crystal_builder()
        polymer_with_lammps = example_5_generate_lammps_files()
        
        print("\n=== Summary ===")
        print("✓ Successfully demonstrated SARW lattice position generation")
        print("✓ Successfully created polymer using RandomWalkBuilder")
        print("✓ Successfully created connected polymer using SAWPolymerBuilder")
        print("✓ Compared SARW with crystal building approaches")
        print("✓ Generated LAMMPS data and input files")
        
        print("\nKey features of the SARW builder:")
        print("- Self-avoiding: prevents overlapping monomers")
        print("- Configurable step length and exclusion radius")
        print("- Suitable for polymer chain generation")
        print("- Follows the AbstractBuilder interface")
        print("- Can create both simple and connected structures")
        print("- Exports to LAMMPS format for molecular dynamics")
        
    except Exception as e:
        print(f"Error running examples: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    main()
