"""Emit a self-contained MolPy Python script from a parsed moltemplate IR.

The output script reconstructs the same ``Atomistic`` + ``ForceField`` that
:func:`build_system` would produce, but through explicit MolPy API calls —
no runtime dependency on the moltemplate parser. Each moltemplate class
maps to a ``build_<ClassName>() -> Atomistic`` function so the emitted
file remains hand-editable.

Usage (CLI)::

    molpy moltemplate convert system.lt system.py

Usage (Python)::

    from molpy.parser.moltemplate import parse_file, emit_python
    emit_python(parse_file("system.lt"), "system.py")
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Iterable

from .builder import (
    _compile_atom_type_replacements,
    _flatten,
    _init_style_registry,
    _resolve_imports,
)
from .ir import (
    ClassDef,
    Document,
    NewStmt,
    ReplaceStmt,
    Transform,
    WriteBlock,
    WriteOnceBlock,
)


def emit_python(
    doc: Document,
    dest: str | Path,
    *,
    base_dir: Path | None = None,
) -> Path:
    """Emit a runnable MolPy Python script from ``doc``.

    Args:
        doc: Parsed moltemplate document (from :func:`parse_file`).
        dest: Output ``.py`` path. Parent directories are created.
        base_dir: Base directory used to resolve ``import`` statements.
            Defaults to ``Path.cwd()``.

    Returns:
        The resolved absolute path written to.
    """
    _init_style_registry()
    if base_dir is None:
        base_dir = Path.cwd()
    doc = _resolve_imports(doc, base_dir)

    out = _emit_document(doc)
    dest_path = Path(dest)
    dest_path.parent.mkdir(parents=True, exist_ok=True)
    dest_path.write_text(out)
    return dest_path.resolve()


_HEADER = '''\
"""Auto-generated by ``molpy moltemplate convert``.

This script reproduces the system described by the original ``.lt`` file
using MolPy's Python API. Edit freely; there is no round-trip back to
moltemplate syntax.
"""

from __future__ import annotations

import math
import random

import molpy as mp
from molpy.core.atomistic import Atomistic
from molpy.parser.moltemplate.builder import _STYLE_REGISTRY, _init_style_registry

_init_style_registry()


def _apply_transform(mol: Atomistic, op: str, args: list[float]) -> None:
    """Apply one moltemplate transform to ``mol`` (shared by build helpers)."""
    if op == "move" and len(args) == 3:
        mol.move(list(args))
    elif op == "rot" and len(args) >= 4:
        angle = math.radians(args[0])
        about = list(args[4:7]) if len(args) >= 7 else None
        mol.rotate([args[1], args[2], args[3]], angle, about=about)
    elif op == "scale" and len(args) == 1:
        mol.scale(args[0])


def _resolve_atom(atoms: dict, ref: str):
    """Resolve a moltemplate ``$atom:...`` reference (handles ``/`` vs ``_``)."""
    if ref in atoms:
        return atoms[ref]
    if "/" in ref and ref.replace("/", "_") in atoms:
        return atoms[ref.replace("/", "_")]
    if "_" in ref and ref.replace("_", "/") in atoms:
        return atoms[ref.replace("_", "/")]
    for k, v in atoms.items():
        if k.endswith("/" + ref) or k.endswith("_" + ref):
            return v
    return None


def _def_style(ff, kind: str, style_name: str):
    """Instantiate and register the concrete Style subclass for ``(kind, name)``."""
    cls = _STYLE_REGISTRY.get((kind, style_name))
    if cls is None:
        raise ValueError(f"unknown {kind} style {style_name!r}")
    return ff.def_style(cls())


def _def_coeff(style, atom_types: list, params: list[float], *, name: str | None = None) -> None:
    """Invoke ``style.def_type`` with a best-effort positional unpack."""
    kwargs = {"name": name} if name is not None else {}
    try:
        style.def_type(*atom_types, *params, **kwargs)
    except TypeError:
        # Fall back: drop the name kwarg for styles that don't accept it.
        style.def_type(*atom_types, *params)
'''

_MAIN_BLOCK = """\
def main() -> None:
    atomistic, ff = build_system()
    print(f"system: {len(list(atomistic.atoms))} atoms, "
          f"{len(list(atomistic.bonds))} bonds, "
          f"{len(list(atomistic.angles))} angles, "
          f"{len(list(atomistic.dihedrals))} dihedrals, "
          f"{len(list(atomistic.impropers))} impropers")
    print(f"force field: {sum(1 for _ in ff.styles.bucket(mp.Style))} styles")


if __name__ == "__main__":
    main()
"""


def _emit_document(doc: Document) -> str:
    classes: dict[str, ClassDef] = {}

    def collect(stmts):
        for s in stmts:
            if isinstance(s, ClassDef):
                classes[s.name] = s
                collect(s.statements)

    collect(doc.statements)

    flat = _flatten(doc)
    replace_rules = _collect_replace_pairs(flat)
    atom_replacements = _compile_atom_type_replacements(replace_rules["atom"])

    parts: list[str] = [_HEADER]
    parts.append(_emit_forcefield_builder(flat))
    for cls_name in _class_emission_order(classes, doc):
        parts.append(
            _emit_class_builder(
                classes[cls_name],
                class_map=classes,
                atom_replacements=atom_replacements,
            )
        )
    parts.append(_emit_system_builder(doc, classes))
    parts.append(_MAIN_BLOCK)
    return "\n\n".join(parts)


# ---------------------------------------------------------------------------
# ForceField builder
# ---------------------------------------------------------------------------

_SET_CHARGE_RE = re.compile(
    r"^\s*set\s+type\s+@atom:(\S+)\s+charge\s+(-?\d+\.?\d*(?:[eE][+-]?\d+)?)\s*$"
)
_COEFF_RE = re.compile(
    r"""
    ^\s*(?P<kind>pair|bond|angle|dihedral|improper)_coeff\s+
    (?P<body>.+?)\s*$
    """,
    re.VERBOSE,
)
_AT_RE = re.compile(r"^@(?:atom|bond|angle|dihedral|improper|pair|mol):(.+)$")
_DOLLAR_RE = re.compile(r"^\$(?:atom|bond|angle|dihedral|improper|mol):(.+)$")
_KIND_PREFIX_RE = re.compile(r"^@(atom|bond|angle|dihedral|improper|pair|mol):")

_BY_TYPE_SECTIONS = {
    "Data Bonds By Type",
    "Data Angles By Type",
    "Data Dihedrals By Type",
    "Data Impropers By Type",
}

_DEFAULTS = {
    "bond": "harmonic",
    "angle": "harmonic",
    "dihedral": "opls",
    "improper": "harmonic",
    "pair": "lj/cut/coul/cut",
}


def _strip_prefix(tok: str) -> str:
    m = _AT_RE.match(tok) or _DOLLAR_RE.match(tok)
    return m.group(1) if m else tok


def _token_kind(tok: str) -> str | None:
    m = _KIND_PREFIX_RE.match(tok)
    return m.group(1) if m else None


def _split_line(line: str) -> list[str]:
    if "#" in line:
        line = line.split("#", 1)[0]
    return line.split()


def _split_style_params(tokens: list[str]) -> tuple[str | None, list[float]]:
    if not tokens:
        return None, []
    try:
        float(tokens[0])
        return None, [float(t) for t in tokens if _is_num(t)]
    except ValueError:
        return tokens[0], [float(t) for t in tokens[1:] if _is_num(t)]


def _is_num(s: str) -> bool:
    try:
        float(s)
        return True
    except ValueError:
        return False


def _collect_replace_pairs(flat: Iterable) -> dict[str, list[tuple[str, str]]]:
    out: dict[str, list[tuple[str, str]]] = {
        "atom": [],
        "bond": [],
        "angle": [],
        "dihedral": [],
        "improper": [],
    }
    for stmt in flat:
        if not isinstance(stmt, ReplaceStmt):
            continue
        for old, new in stmt.pairs:
            kind = _token_kind(old)
            if kind in out:
                out[kind].append((_strip_prefix(old), _strip_prefix(new)))
    return out


def _style_var(kind: str, style_name: str) -> str:
    sanitised = re.sub(r"[^A-Za-z0-9_]", "_", style_name)
    return f"_{kind}_style_{sanitised}"


def _emit_forcefield_builder(flat: list) -> str:
    lines: list[str] = [
        "def build_forcefield() -> mp.AtomisticForcefield:",
        '    """Reconstruct the force field from the original ``.lt`` file."""',
        '    ff = mp.AtomisticForcefield(name="moltemplate", units="real")',
        "    ff.metadata = {}",
        "    atom_style = ff.def_atomstyle('full')",
        "    def _atom(name, **kw):",
        "        existing = atom_style.get_type_by_name(name)",
        "        if existing is not None:",
        "            for k, v in kw.items():",
        "                existing[k] = v",
        "            return existing",
        "        return atom_style.def_type(name=name, type_=name, **kw)",
    ]
    preserved_sections: dict[str, list[str]] = {}
    replace_pairs: list[tuple[str, str]] = []
    bytype_lines: dict[str, list[str]] = {k: [] for k in _BY_TYPE_SECTIONS}

    for stmt in flat:
        if isinstance(stmt, ReplaceStmt):
            replace_pairs.extend(stmt.pairs)
            continue
        if not isinstance(stmt, (WriteBlock, WriteOnceBlock)):
            continue
        section = stmt.section
        if section == "Data Masses":
            lines.extend(_emit_data_masses(stmt.body_lines))
        elif section in ("Data Charges", "In Charges"):
            lines.extend(_emit_data_charges(stmt.body_lines))
        elif section == "In Settings":
            lines.extend(_emit_in_settings(stmt.body_lines))
        elif section in _BY_TYPE_SECTIONS:
            bytype_lines[section].extend(stmt.body_lines)
        else:
            preserved_sections.setdefault(section, []).extend(stmt.body_lines)

    for section, body in preserved_sections.items():
        lines.append(f"    ff.metadata.setdefault({section!r}, []).extend({body!r})")
    for section, body in bytype_lines.items():
        if body:
            lines.append(
                f"    ff.metadata.setdefault({section!r}, []).extend({body!r})"
            )

    if replace_pairs:
        lines.append("    ff.metadata['_replace_map'] = {")
        lines.append("        'atom': [], 'bond': [], 'angle': [],")
        lines.append("        'dihedral': [], 'improper': [],")
        lines.append("    }")
        for old, new in replace_pairs:
            kind = _token_kind(old)
            if kind is None:
                continue
            lines.append(
                f"    ff.metadata['_replace_map'][{kind!r}].append("
                f"({_strip_prefix(old)!r}, {_strip_prefix(new)!r}))"
            )

    lines.append("    return ff")
    return "\n".join(lines)


def _emit_data_masses(body: list[str]) -> list[str]:
    out: list[str] = []
    for ln in body:
        toks = _split_line(ln)
        if len(toks) < 2 or not toks[0].startswith("@atom:"):
            continue
        name = _strip_prefix(toks[0])
        try:
            mass = float(toks[1])
        except ValueError:
            continue
        out.append(f"    _atom({name!r}, mass={mass!r}, charge=0.0)")
    return out


def _emit_data_charges(body: list[str]) -> list[str]:
    out: list[str] = []
    for ln in body:
        m = _SET_CHARGE_RE.match(ln)
        if m:
            name, charge = m.group(1), float(m.group(2))
            out.append(f"    _atom({name!r}, charge={charge!r})")
    return out


def _emit_in_settings(body: list[str]) -> list[str]:
    out: list[str] = []
    style_created: set[tuple[str, str]] = set()
    for raw in body:
        m = _COEFF_RE.match(raw)
        if not m:
            continue
        kind = m.group("kind")
        toks = _split_line(m.group("body"))
        if len(toks) < 2:
            continue

        if kind == "pair":
            if not (toks[0].startswith("@atom:") and toks[1].startswith("@atom:")):
                continue
            name_i = _strip_prefix(toks[0])
            name_j = _strip_prefix(toks[1])
            if "*" in name_i or "*" in name_j:
                continue
            rest = toks[2:]
            style_name, params = _split_style_params(rest)
            style_name = style_name or _DEFAULTS[kind]
            var = _style_var(kind, style_name)
            stamp = (kind, style_name)
            if stamp not in style_created:
                out.append(f"    {var} = _def_style(ff, {kind!r}, {style_name!r})")
                style_created.add(stamp)
            out.append(
                f"    _def_coeff({var}, [_atom({name_i!r}), _atom({name_j!r})], "
                f"{params!r})"
            )
            continue

        # bond / angle / dihedral / improper
        prefix = _strip_prefix(toks[0])
        rest = toks[1:]
        style_name, params = _split_style_params(rest)
        style_name = style_name or _DEFAULTS.get(kind, "harmonic")
        var = _style_var(kind, style_name)
        stamp = (kind, style_name)
        if stamp not in style_created:
            out.append(f"    {var} = _def_style(ff, {kind!r}, {style_name!r})")
            style_created.add(stamp)
        arity = {"bond": 2, "angle": 3, "dihedral": 4, "improper": 4}[kind]
        placeholder = ", ".join(f"_atom({prefix + '_' + s!r})" for s in "ijkl"[:arity])
        out.append(
            f"    _def_coeff({var}, [{placeholder}], {params!r}, name={prefix!r})"
        )
    return out


# ---------------------------------------------------------------------------
# Class builders
# ---------------------------------------------------------------------------

_DATA_ATOM_RE = re.compile(
    r"""
    ^\s*\$atom(?::(?P<id>\S+))?\s+
    (?:\$mol(?::\S+)?\s+)?
    @atom(?::(?P<type>\S+))?\s+
    (?P<charge>-?\d+\.?\d*(?:[eE][+-]?\d+)?)\s+
    (?P<x>-?\d+\.?\d*(?:[eE][+-]?\d+)?)\s+
    (?P<y>-?\d+\.?\d*(?:[eE][+-]?\d+)?)\s+
    (?P<z>-?\d+\.?\d*(?:[eE][+-]?\d+)?)
    """,
    re.VERBOSE,
)
_DATA_BOND_TYPED_RE = re.compile(
    r"^\s*\$bond:(?P<id>\S+)\s+@bond:(?P<type>\S+)\s+\$atom:(?P<a>\S+)\s+\$atom:(?P<b>\S+)"
)
_DATA_BOND_LIST_RE = re.compile(
    r"^\s*\$bond:(?P<id>\S+)\s+\$atom:(?P<a>\S+)\s+\$atom:(?P<b>\S+)"
)
_DATA_ANGLE_RE = re.compile(
    r"^\s*\$angle:(?P<id>\S+)\s+@angle:(?P<type>\S+)\s+\$atom:(?P<a>\S+)\s+\$atom:(?P<b>\S+)\s+\$atom:(?P<c>\S+)"
)
_DATA_DIHE_RE = re.compile(
    r"^\s*\$dihedral:(?P<id>\S+)\s+@dihedral:(?P<type>\S+)\s+"
    r"\$atom:(?P<a>\S+)\s+\$atom:(?P<b>\S+)\s+\$atom:(?P<c>\S+)\s+\$atom:(?P<d>\S+)"
)
_DATA_IMPR_RE = re.compile(
    r"^\s*\$improper:(?P<id>\S+)\s+@improper:(?P<type>\S+)\s+"
    r"\$atom:(?P<a>\S+)\s+\$atom:(?P<b>\S+)\s+\$atom:(?P<c>\S+)\s+\$atom:(?P<d>\S+)"
)


def _class_emission_order(
    classes: dict[str, ClassDef],
    doc: Document,
) -> list[str]:
    order: list[str] = []
    seen: set[str] = set()

    def visit(name: str, stack: tuple[str, ...] = ()) -> None:
        if name in seen or name in stack or name not in classes:
            return
        cls = classes[name]
        for base in cls.bases:
            visit(base, stack + (name,))
        for s in cls.statements:
            if isinstance(s, NewStmt):
                if s.class_name == "random":
                    for ch in s.random_choices:
                        visit(ch.class_name, stack + (name,))
                else:
                    visit(s.class_name, stack + (name,))
        if name not in seen:
            seen.add(name)
            order.append(name)

    for name in classes:
        visit(name)
    return order


def _apply_atom_replace_static(raw_type: str, replacements) -> str:
    if not replacements or not raw_type:
        return raw_type
    for pat, new in replacements:
        if pat.match(raw_type):
            return new
    return raw_type


def _resolve_class_body(
    cls: ClassDef, class_map: dict[str, ClassDef], stack: tuple[str, ...] = ()
) -> list:
    if cls.name in stack:
        return []
    body: list = []
    for base in cls.bases:
        base_cls = class_map.get(base)
        if base_cls is None:
            continue
        body.extend(_resolve_class_body(base_cls, class_map, stack + (cls.name,)))
    for s in cls.statements:
        if not isinstance(s, ClassDef):
            body.append(s)
    return body


def _emit_class_builder(
    cls: ClassDef,
    *,
    class_map: dict[str, ClassDef],
    atom_replacements,
) -> str:
    fn_name = _sanitize_ident("build_" + cls.name)
    lines: list[str] = [
        f"def {fn_name}() -> Atomistic:",
        f'    """Template builder for moltemplate class ``{cls.name}``."""',
        "    tmpl = Atomistic()",
        "    atoms: dict[str, object] = {}",
    ]

    effective = _resolve_class_body(cls, class_map)

    # Pass 1: inner `new` statements
    for s in effective:
        if isinstance(s, NewStmt) and s.class_name != "random":
            sub_fn = _sanitize_ident("build_" + s.class_name)
            lines.append(f"    sub = {sub_fn}()")
            for t in s.transforms:
                lines.append(f"    {_transform_call('sub', t)}")
            lines.extend(
                [
                    "    for _a in list(sub.atoms):",
                    "        _base = _a.get('name', '')",
                    f"        _key = {s.instance_name!r} + '/' + _base",
                    "        _a['name'] = _key",
                    "        atoms[_key] = _a",
                    "    tmpl += sub",
                ]
            )

    # Pass 2: Data Atoms / Bonds / Angles / Dihedrals / Impropers
    anon = 0
    for s in effective:
        if not isinstance(s, (WriteBlock, WriteOnceBlock)):
            continue
        if s.section == "Data Atoms":
            for ln in s.body_lines:
                m = _DATA_ATOM_RE.match(ln)
                if not m:
                    continue
                aid = m.group("id")
                if aid is None:
                    aid = f"_anon{anon}"
                    anon += 1
                eff_type = _apply_atom_replace_static(
                    m.group("type") or "", atom_replacements
                )
                lines.append(
                    f"    _a = tmpl.def_atom(name={aid!r}, type={eff_type!r}, "
                    f"charge={float(m.group('charge'))!r}, "
                    f"xyz=[{float(m.group('x'))!r}, {float(m.group('y'))!r}, "
                    f"{float(m.group('z'))!r}])"
                )
                lines.append(f"    atoms[{aid!r}] = _a")
        elif s.section in ("Data Bonds", "Data Bond List"):
            for ln in s.body_lines:
                m = _DATA_BOND_TYPED_RE.match(ln)
                if m:
                    lines.append(
                        f"    _a1 = _resolve_atom(atoms, {m.group('a')!r}); "
                        f"_a2 = _resolve_atom(atoms, {m.group('b')!r})"
                    )
                    lines.append("    if _a1 is not None and _a2 is not None:")
                    lines.append(
                        f"        tmpl.def_bond(_a1, _a2, type={m.group('type')!r})"
                    )
                    continue
                m = _DATA_BOND_LIST_RE.match(ln)
                if m:
                    lines.append(
                        f"    _a1 = _resolve_atom(atoms, {m.group('a')!r}); "
                        f"_a2 = _resolve_atom(atoms, {m.group('b')!r})"
                    )
                    lines.append("    if _a1 is not None and _a2 is not None:")
                    lines.append('        tmpl.def_bond(_a1, _a2, type="")')
        elif s.section == "Data Angles":
            for ln in s.body_lines:
                m = _DATA_ANGLE_RE.match(ln)
                if m:
                    lines.append(
                        f"    _a1 = _resolve_atom(atoms, {m.group('a')!r}); "
                        f"_a2 = _resolve_atom(atoms, {m.group('b')!r}); "
                        f"_a3 = _resolve_atom(atoms, {m.group('c')!r})"
                    )
                    lines.append("    if _a1 and _a2 and _a3:")
                    lines.append(
                        f"        tmpl.def_angle(_a1, _a2, _a3, type={m.group('type')!r})"
                    )
        elif s.section == "Data Dihedrals":
            for ln in s.body_lines:
                m = _DATA_DIHE_RE.match(ln)
                if m:
                    lines.append(
                        f"    _a1 = _resolve_atom(atoms, {m.group('a')!r}); "
                        f"_a2 = _resolve_atom(atoms, {m.group('b')!r}); "
                        f"_a3 = _resolve_atom(atoms, {m.group('c')!r}); "
                        f"_a4 = _resolve_atom(atoms, {m.group('d')!r})"
                    )
                    lines.append("    if _a1 and _a2 and _a3 and _a4:")
                    lines.append(
                        f"        tmpl.def_dihedral(_a1, _a2, _a3, _a4, "
                        f"type={m.group('type')!r})"
                    )
        elif s.section == "Data Impropers":
            for ln in s.body_lines:
                m = _DATA_IMPR_RE.match(ln)
                if m:
                    lines.append(
                        f"    _a1 = _resolve_atom(atoms, {m.group('a')!r}); "
                        f"_a2 = _resolve_atom(atoms, {m.group('b')!r}); "
                        f"_a3 = _resolve_atom(atoms, {m.group('c')!r}); "
                        f"_a4 = _resolve_atom(atoms, {m.group('d')!r})"
                    )
                    lines.append("    if _a1 and _a2 and _a3 and _a4:")
                    lines.append(
                        f"        tmpl.def_improper(_a1, _a2, _a3, _a4, "
                        f"type={m.group('type')!r})"
                    )
    lines.append("    return tmpl")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# System assembly
# ---------------------------------------------------------------------------


def _emit_system_builder(doc: Document, classes: dict[str, ClassDef]) -> str:
    lines: list[str] = [
        "def build_system() -> tuple[Atomistic, mp.AtomisticForcefield]:",
        '    """Assemble the full system and apply By-Type rules."""',
        "    ff = build_forcefield()",
        "    system = Atomistic()",
    ]
    for stmt in doc.statements:
        if not isinstance(stmt, NewStmt):
            continue
        if stmt.class_name == "random":
            lines.extend(_emit_random_new(stmt))
        else:
            lines.extend(_emit_concrete_new(stmt, classes))

    lines.extend(
        [
            "    from molpy.parser.moltemplate.builder import "
            "_apply_by_type_to_system as _apply_bt",
            "    if len(list(system.bonds)) > 0:",
            "        try:",
            "            _existing_angles = len(list(system.angles))",
            "            _existing_dihe = len(list(system.dihedrals))",
            "            system = system.get_topo(",
            "                gen_angle=_existing_angles == 0,",
            "                gen_dihe=_existing_dihe == 0,",
            "            )",
            "        except Exception:",
            "            pass",
            "    try:",
            "        _apply_bt(system, ff)",
            "    except Exception:",
            "        pass",
            "    return system, ff",
        ]
    )
    return "\n".join(lines)


def _emit_concrete_new(stmt: NewStmt, classes: dict[str, ClassDef]) -> list[str]:
    if stmt.class_name not in classes:
        return [f"    # skipped unknown class: {stmt.class_name!r}"]
    fn = _sanitize_ident("build_" + stmt.class_name)
    count = max(stmt.count, 1)
    grid = stmt.arrays
    lines: list[str] = [
        f"    # {stmt.instance_name} = new {stmt.class_name}  "
        f"(count={count}, arrays={[d.count for d in grid]})",
    ]
    if not grid:
        for _ in range(count):
            lines.append(f"    _m = {fn}()")
            for t in stmt.transforms:
                lines.append(f"    {_transform_call('_m', t)}")
            lines.append("    system += _m")
        return lines

    indent = "    "
    lines.append(f"{indent}for _rep in range({count}):")
    indent += "    "
    dim_vars: list[tuple[str, Transform | None]] = []
    for d, dim in enumerate(grid):
        lines.append(f"{indent}for _k{d} in range({dim.count}):")
        indent += "    "
        dim_vars.append((f"_k{d}", dim.transform))
    lines.append(f"{indent}_m = {fn}()")
    for t in stmt.transforms:
        lines.append(f"{indent}{_transform_call('_m', t)}")
    for var, tr in dim_vars:
        if tr is None:
            continue
        lines.append(_scaled_transform_line(tr, var, indent))
    lines.append(f"{indent}system += _m")
    return lines


def _scaled_transform_line(tr: Transform, var: str, indent: str) -> str:
    if tr.op == "move" and len(tr.args) == 3:
        coords = ", ".join(f"{var}*{a!r}" for a in tr.args)
        return f"{indent}_m.move([{coords}])"
    if tr.op == "rot" and len(tr.args) >= 4:
        angle = f"math.radians({var}*{tr.args[0]!r})"
        axis = f"[{tr.args[1]!r}, {tr.args[2]!r}, {tr.args[3]!r}]"
        about = (
            f", about=[{tr.args[4]!r}, {tr.args[5]!r}, {tr.args[6]!r}]"
            if len(tr.args) >= 7
            else ""
        )
        return f"{indent}_m.rotate({axis}, {angle}{about})"
    if tr.op == "scale" and len(tr.args) == 1:
        return f"{indent}_m.scale({var}*{tr.args[0]!r})"
    return f"{indent}# unsupported scaled transform: {tr.op}({tr.args})"


def _emit_random_new(stmt: NewStmt) -> list[str]:
    grid = 1
    for dim in stmt.arrays:
        grid *= max(dim.count, 0)
    if not stmt.arrays:
        grid = 1
    grid *= max(stmt.count, 1)
    choices_parts: list[str] = []
    for ch in stmt.random_choices:
        fn = _sanitize_ident("build_" + ch.class_name)
        trs = [(t.op, list(t.args)) for t in ch.transforms]
        choices_parts.append(f"({fn!r}, {trs!r})")
    weights = list(stmt.random_weights) or [1.0] * len(stmt.random_choices)
    seed = stmt.random_seed
    lines: list[str] = [
        f"    # weighted random mixture for {stmt.instance_name}",
        f"    _choices = [{', '.join(choices_parts)}]",
        f"    _weights = {weights!r}",
        f"    _prng = random.Random({seed!r}) if {seed!r} is not None else random.Random()",
        f"    _n = {grid}",
        "    _int_weights = all(float(w).is_integer() and w >= 0 for w in _weights)",
        "    if _int_weights and sum(int(w) for w in _weights) == _n:",
        "        _sel = []",
        "        for _i, _w in enumerate(_weights): _sel.extend([_i] * int(_w))",
        "        _prng.shuffle(_sel)",
        "    else:",
        "        _total = float(sum(_weights)) or 1.0",
        "        _probs = [w/_total for w in _weights]",
        "        _sel = _prng.choices(range(len(_choices)), weights=_probs, k=_n)",
        "    for _idx in _sel:",
        "        _builder_name, _choice_transforms = _choices[_idx]",
        "        _m = globals()[_builder_name]()",
        "        for _op, _args in _choice_transforms:",
        "            _apply_transform(_m, _op, _args)",
    ]
    for t in stmt.transforms:
        lines.append(f"        {_transform_call('_m', t)}")
    lines.append("        system += _m")
    return lines


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _transform_call(target: str, tr: Transform) -> str:
    if tr.op == "move" and len(tr.args) == 3:
        return f"{target}.move([{tr.args[0]!r}, {tr.args[1]!r}, {tr.args[2]!r}])"
    if tr.op == "rot" and len(tr.args) >= 4:
        angle = f"math.radians({tr.args[0]!r})"
        axis = f"[{tr.args[1]!r}, {tr.args[2]!r}, {tr.args[3]!r}]"
        about = (
            f", about=[{tr.args[4]!r}, {tr.args[5]!r}, {tr.args[6]!r}]"
            if len(tr.args) >= 7
            else ""
        )
        return f"{target}.rotate({axis}, {angle}{about})"
    if tr.op == "scale" and len(tr.args) == 1:
        return f"{target}.scale({tr.args[0]!r})"
    return f"# unsupported transform: {tr.op}({tr.args})"


def _sanitize_ident(s: str) -> str:
    out = re.sub(r"[^A-Za-z0-9_]", "_", s)
    if out[:1].isdigit():
        out = "_" + out
    return out
