name: publish_conda

on: [release]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: maxibor/conda-package-publish-action@v1.1
      with:
        subDir: 'config'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
